# Generated by Django 3.1 on 2020-09-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_library_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_borrowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.library_books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.library_users')),
            ],
        ),
    ]
