# Generated by Django 3.1 on 2020-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_borrowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_users',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
